const messages = {
    en: {
        shared: {
        },
        common: {
            loading: 'Loading...',
            previous: 'Previous',
            next: 'Next',
            close: 'Close',
            save: 'Save',
            cancel: 'Cancel',
            confirm: 'Confirm',
            error: 'Error',
            success: 'Success'
        },
        header:{
            documents:'Documents',
            company:'Company',
                company_1:'Legal validity of electronic',
                company_1_2:'document',
                company_2:'Accreditations',
                company_3:'Conflict resolution of',
                company_3_2:'electronic documents',
                company_4:'Frequent questions',
                company_5:'Our company',
            myaccount:'My account',
                login:'Log in',
                join:'Sign in',

                myinfo:'My Basic Information',
                mydocs:'My Documentation',
                mylog:'My logo',
                mysing:'My signature',
                mypass:'My password',
                docs_sing:'Documents to sign',
                contacts:'Contact directory',
                buy_credits:'Buy credits',
                history_pay:'Payment history',
                logout:'Log out',

                sing_documents:'SIGN DOCUMENTS',
                video_prmo:'PROMOTIONAL VIDEO',

                hi:'Hi',
                credits:'Available credits',

                placesearch:'SEARCH THE CONTRACT YOU NEED',
                search:'LOOK FOR',
                advisory:'ADVISORY',
                search_placeholder:'Search...',
        },
        home:{
            validator:'Validator',
            how_work:'How does it work?',
            step_one:'1.- Upload what you need to sign.',
            step_two:'2.- Choose who should sign and click send.',
            step_three:'3.- Those involved receive a link to access and sign digitally. And our system creates 1 secure and legally valid time-stamped file.',
            advantages:'Advantages',
            advantages_one:'Documents and images certified with advanced electronic signature through the technology of Seguridata Privada SA de CV.',
            advantages_two:'Documents and images certified with a time stamp through the technology of Seguridata Privada SA de CV.',
            advantages_three:'Documents certified before NOM 151 SCFI 2016 of the Ministry of Economy and TLA',
            advantages_four:'Our documents have an arbitration clause of the CAE; Business Arbitration Center',
            credits:'Credits',
            pay_with:'PAY WITH',
            desing:'Design and implement NOTARYNET® in your business.',
            accreditations:'Accreditations and certificates',
            accreditations_one:'Digital Certificates',
            accreditations_two:'Certificates NOM-151',
            accreditations_three:'Time Stamps',
            accreditations_four:'Digitization of Documents in Physical Support',

            modal:{
                validate:'Validate your document',
                one:'Access the following link',
                validator:'Validator Seguridata',
                two:'Publish in the "Select file" tab the 2 files of your Certified Document that you can download from the "My account / Documents / Signed" section from the buttons: "Download PDF" and "Download NOM".',
                three:'The system of our PSC Seguridata will show you the information of the uploaded files. This will show that your document is valid and correct.'
            }
        },
        footer:{
            support:'Support by the Federal Law of Electronic Signature, Commercial Code and State Laws of Electronic Media',
            information:'Information',
            credits:'Credits',
            terms:'Terms and Conditions',
            notice:'Notice of Privacy',
            request:'Request your invoice',
            phone:'Phone',
            email:'Email',
            footer_one:'All the documents issued have the model clause for expedited and low-claim arbitration of the CAE; Business Arbitration Center.',
            footer_one_two:'For more information go to',

            footer_two:'Confirm with our PSC certification service provider (Seguridata Privada S.A. de C.V.) the validity of the documents signed by NOTARYNET in the following link',
            footer_three:'NOTARYNET is developed and managed by',
        },
        detail:{
            cost:'Cost',
            credits:'credits',
            description:'Description',
            use_doc:'Use this document',
            display_format:'Display format',
        },
        contact:{
            contact:'Contact',
            qustions:'Do you have questions?',
            send_ms:'Send us a message or contact us.',
            address:'Address',
            phone:'Phone',
            email:'Email',
            follow:'Follow us',
            name_input:'Name',
            email_input:'Email',
            msg:'Message',
            send:'SEND',


        },
        requestinvoice:{
            request_invoice:'Request your invoice',
            date:'Date of purchase',
            email:'Email',
            business:'Business name',
            address:'Address',
            state:'State',
            select_option:'Select an option',
            town:'Town',
            zipcode:'Zip code',
            send:'SEND',
            accept:'Accept',
        },
        login:{
            login:'Log in',
            email:'Email',
            password:'Password',
            sign_up:'You do not have an account? Sign up.',
            forgot_pass:'Forgot your password?',
            access:'Log in',
        },
        resetpassword:{
            recover:'Recover password',
            write:'Write your email. We will send you a message with the steps to recover your password.',
            email:'Email',
            remember:'Do you remember your password? To access!',
            accept:'Accept',
        },
        register:{
            register:'Register',
            basic_info:'BASIC INFORMATION',
            fullname:'Full name',
            phone:'Phone',
            write_phone:'Write your phone',
            email:'Email',
            write_email:'Write your email',

            to_whom:'TO WHOM DO YOU ISSUE DOCUMENTS?',
            to_whose:'IN WHOSE NAME WILL YOU SIGN THIS DOCUMENT?',
            physical_p:'Physical person',
            moral_p:'Moral person',
            businessname:'Business name',
            write_businessname:'Write your company name',
            location_company:'LOCATION OF THE COMPANY',
            location:'LOCATION',
            street:'Street',
            write_street:'Write the street',
            num_ext:'Outdoor Number',
            write_num_ext:'Write the outdoor Number',
            num_int:'Interior number',
            write_num_int:'Write the interior number',
            neighborhood:'Neighborhood',
            write_neighborhood:'Write the neighborhood',
            zip_code:'Zip code',
            write_zip_code:'Write the zip code',
            state:'State',
            town:'Town',
            select_option:'Select an option',

            access_sistem:'ACCESS TO THIS SYSTEM, CREATE A PASSWORD',

            pass:'Password',
            write_pass:'Enter your password',
            confim_pass:'Confirm your password',
            confirm_pass:'Confirm your password',

            the_sing:'Then sign inside the box as similar as possible to the signature of your official identification document (current INE or Valid Passport)',
            add_signature:'ADD A SIGNATURE',
            quit_signature:'Remove signature',
            terms:'I have read and accept the Terms and Conditions of the',
            already_account:'Already have an account?',
            acreate_account_sing:'Create account and proceed to signing',
            create_account:'Create an account',

        },
        account:{
            index:{
                documents:'Documents',
                welcome:'Welcome',
                myinfo:'My Basic Information',
                mydocs:'My Documentation',
                mylog:'My logo',
                mysing:'My signature',
                mypass:'My password',
                docs_sing:'Documents to sign',
                contacts:'Contact directory',
                buy_credits:'Buy credits',
                history_pay:'Payment history',
                logout:'Log out',
            },
            basic_info:{
                my_basic_info:'My basic information',
                subtitle:'All information is mandatory and will be verified, otherwise documents cannot be issued.',
                email:'Email',
                fullname:'Full name',
                phone:'Phone',
                street:'Street',
                num_ext:'Outdoor Number',
                num_int:'Interior number',
                neighborhood:'Neighborhood',
                zip_code:'Zip code',
                state:'State',
                town:'Town',
                select_option:'Select an option',
                save_changes:'Save Changes',
                foreing:'My address is outside of Mexico.',
                country:'Country',


            },
            mylogo:{
                mylogo:'My logo (Optional)',
                subtitle:'Add the logo of your trademark or company so that it appears on the documents to be certified, this logo will appear on top of them.',
                extention:'Add a JPG or PNG image',
                quit:'Remove',
                save_logo:'Save logo',

            },
            mysignature:{
                title:'My signature',
                subtitle:'This rubric will be taken as a reference for the signing of all the next documents you make.',
                new_sing:'ADD NEW SIGNATURE',
                save_sing:'Save signature',
                sing_equal:'Sign the same as in your INE',
                save:'Save',
                clean:'Clean'
            },
            password:{
                title:'My Password',
                current_password:'Enter your current password',
                new_password:'Enter your new password',
                new_password_confirm:'Please retype your new password',
                save_password:'Change password',
            },
            contacts:{
                title:'Contacts',
                add_contact:'Add contact',
                subtitle:'The contacts are the ones who will fill out the document with you, they will receive an email to access the NOTARIONET system and fill in their data to sign digitally',
                search:'Search contact...',
                no_contacts:'There are no contacts in your directory',

                email:'Email',
                full_name:'Full name',
                phone:'Phone',
                contact_exist:'This contact already exists in our database, you no longer need to enter their information',
                edit_contact:'Edit contact',

                neighborhood:'Neighborhood',
                zip_code:'Zip code',
            },
            buycredits:{
                title:'Buy Credits',
                select:'Select',
                selected:'Selected',
                select_option:'Select an option',
                info_pay:'Payment information',
                deposit:'Deposit - Transfer',
                card:'Credit/debit card',
                card_details:'Card details',
                bank:'BANK',
                headline:'HEADLINE',
                send_proof:'Please send us the proof of payment to the following email',
                process_order:'Process order',
                done:'Done',
            },
            history_payment:{
                title:'Payment history',
                id_compra:'ID de compra',
                package:'Package purchased',
                total_credits:'Total credits',
                date:'Date and time of purchase',
                validity:'Validity',
                status:'Status',
                payed:'Paid',
                outstanding:'Outstanding',
                accept:'Accept',
            },

            documents:{
                title:'Documents',
                subtitle:'Manage and track all your digital documents',
                search_placeholder:'Search documents...',
                all_documents:'All',
                signed:'Signed',
                pending:'Pending',
                cancelled:'Cancelled',
                total_documents:'Total Documents',
                no_documents:'No documents found',
                no_documents_description:'You haven\'t created any documents yet. Start by creating your first document.',
                create_first_document:'Create First Document',
                view:'View',
                sign:'Sign',
                download:'Download',
                cancel:'Cancel',
                cancel_document:'Cancel Document',
                cancel_confirm:'Are you sure you want to cancel this document? This action cannot be undone.',
                cancelled_successfully:'Document cancelled successfully',
                cancel_error:'Error cancelling document',
                load_error:'Error loading documents',
                view_document:'View Document',
                aviable_credits:'Available credits',
                new_document:'New document',
                buy_credits:'Buy credits',
                complete_info:'You must fill in your information',
                account_auth:'Your account account must be authorized before creating a document',

                waiting_signature:'Waiting signature',
                pending_sign:'Pending sign',
                resend:'Resend',

                document_type:'Document type',
                date_realization:'Date of realization',
                contractor:'Contractor',
                counterpart:'Counterpart',
                signature_date:'Signature date of',
                cancel:'Cancel document',
                sign:'Sign',
                view_document:'View document',
                cancellation_folio:'Cancellation folio',
                date_cacelation:'Cancellation date',

                modal_sing_title:'Click to sign securely',
                modal_sing_subtitle:'This document is not valid until fully signed',
                accept:'Accept',

                folder_destination:'Destination folder',
                select_option:'Select an option',
                move:'Move',
                newfolder:'New folder',
                all:'All',
                move_to_folder:'Move to folder',
                delete_folder:'Delete folder',
                folder:'Folder',
                folder_name:'Folder name',
                save:'Save',
                sign_less:'You must register your signature before signing'
            },



        },
        credits:{
            title:'Select a credit package',
            select:'Select',
            selected:'Selected',
            select_option:'Select an option',
            info_pay:'Payment information',
            deposit:'Deposit - Transfer',
            card:'Credit/debit card',
            card_details:'Card details',
            bank:'BANK',
            headline:'HEADLINE',
            send_proof:'Please send us the proof of payment to the following email',
            process_order:'Process order',
            process_pay:'Process payment',
            done:'Done',
        },
        new_document:{
            title:'New document',
            select_type:'Select the type of document',
            select_option:'Select an option',
            document_type:'Document type',
            description:'Description',
            description_con:'You can sign screenshots of conversations, text messages, emails and/or any other multimedia media that you wish to give legal validity to.',
            next:'Next',
            previous:'Previous',
            counterpart_data:'Counterparty data',
            select_contacto:'Select an existing contact in your directory, or add a new one. The contacts are those who sign the certified document:',
            search_contact:'Find contact...',
            i_manager:'I am the manager of this document, I do not make signatures.',
            phone:'Phone',
            email:'Email',
            full_name:'Full name',
            address:'Address',
            no_contacts:'There are no contacts in your directory',
            add_contact:'Add contact',
            add_info_complete:'Add the following information to complete your document',
            document_body:'Document body',
            select_element:'Select the item to sign',
            i_understand:'I understand that the image or document to be published is done in good faith and that NOTARIONET has no responsibility for what is published.',
            reference_images:'Reference images',
            add_image:'Add image',
            images_comments:'Comments',
            images_delete:'Delete',
            review:'Review',
            legal_support:'LEGAL SUPPORT: The image shown below is certified by the time stamp and digital certificate of NOTARIONET and complies with the NOM151 SCFI 2016 standards of the Ministry of Economy, the digital certificate issuance service DOF 06/20/2011, the service of issuance of digital time stamps of DOF 12/14/2011 and the physical document digitization service as a legally authorized third party TLA DOF 12/03/2019',
            finish:'Finish',
            sing:'Sign',
            finished_document:'Finished document',
            completed_successfully:'Completed successfully',
            signed_document:'Signed document',
            signed_media:'Signed_media',
            go_to_documents:'Go to the "Documents" section of your session to be able to view it.',
            signed_document_success:'Document successfully signed',
            will_send:'It will be sent to your counterpart to be signed. You can see this document in the "Documents" section of your session',

            no_valid:'This document is not valid until fully signed',
            image:'Image',
            the_sign:'Then sign inside the box similar to the initial reference signature you captured on record. If the signature is not similar, you will not be able to certify documents',

        },


    },
    es: {
        shared: {
        },
        common: {
            loading: 'Cargando...',
            previous: 'Anterior',
            next: 'Siguiente',
            close: 'Cerrar',
            save: 'Guardar',
            cancel: 'Cancelar',
            confirm: 'Confirmar',
            error: 'Error',
            success: 'Éxito'
        },
        header:{
            documents:'Documentos',
            company:'Empresa',
                company_1:'Validez legal de documento',
                company_1_2:'electrónico',
                company_2:'Acreditaciones',
                company_3:'Solución de conflictos de',
                company_3_2:'documentos electrónicos',
                company_4:'Preguntas frecuentes',
                company_5:'Nuestra empresa',
            myaccount:'Mi cuenta',
                login:'Iniciar sesión',
                join:'Registrarse',

                myinfo:'Mi Información básica',
                mydocs:'Mi Documentación',
                mylog:'Mi Logo',
                mysing:'Mi firma',
                mypass:'Mi contraseña',
                docs_sing:'Documentos a firmar',
                contacts:'Directorio de contactos',
                buy_credits:'Comprar créditos',
                history_pay:'Historico de pagos',
                logout:'Cerrar sesión',

                sing_documents:'FIRMAR DOCUMENTOS',
                video_prmo:'VIDEO PROMO',

                hi:'Hola',
                credits:'créditos disponibles',

                placesearch:'BUSCA EL CONTRATO QUE NECESITES',
                search:'BUSCAR',
                advisory:'ASESORÍA',
                search_placeholder:'Buscar...',
        },
        home:{
            validator:'Validador',
            how_work:'¿Cómo funciona?',
            step_one:'1.- Sube lo que necesites firmar.',
            step_two:'2.- Escoge quien debe firmar y da click en enviar.',
            step_three:'3.- Los involucrados reciben una liga para acceder y firmar de manera digital. Y nuestro sistema crea 1 archivo con sello de tiempo seguro y valido legalmente.',
            advantages:'Ventajas',
            advantages_one:'Documentos e imágenes certificadas con firma electrónica avanzada por medio de la tecnologia de Seguridata Privada SA de CV.',
            advantages_two:'Documentos e imágenes certificadas con sello de tiempo por medio de la tecnologia de Seguridata Privada SA de CV.',
            advantages_three:'Documentos certificados ante la NOM 151 SCFI 2016 de la Secretaría de economía y TLA',
            advantages_four:'Nuestros documentos cuentan con cláusula arbitral del CAE; Centro de Arbitraje Empresarial',

            credits:'Créditos',
            pay_with:'PAGA CON',
            desing:'Diseña e implementa NOTARYNET® en tu negocio.',
            accreditations:'Acreditaciones y certificados',
            accreditations_one:'Certificados Digitales',
            accreditations_two:'Constancias NOM-151',
            accreditations_three:'Sellos de Tiempo',
            accreditations_four:'Digitalización de Documentos en Soporte Físico',
            modal:{
                validate:'Valida tu documento',
                one:'Accede al siguiente enlace',
                validator:'Validador Seguridata',
                two:'Publica en la pestaña de “Seleccionar archivo” los 2 archivos de tu Documento Certificado que podras descargar de la sección de “Mi cuenta / Documentos / Firmados” desde los botones: “Descargar PDF” y “Descargar NOM”.',
                three:'El sistema de nuestro PSC Seguridata te mostrará la información de los archivos cargados. Esto mostrara que tu documento es valido y correcto.'
            }
        },
        footer:{
            support:'Respaldo por la Ley Federal de Firma Electrónica, Código de Comercio y Leyes Estatales de Medios Electrónicos',
            information:'Información',
            credits:'Créditos',
            terms:'Términos y condiciones',
            notice:'Aviso de privacidad',
            request:'Solicita tu factura',
            phone:'Teléfono',
            email:'Correo',
            footer_one:'Todos los documentos expedidos cuentan con la cláusula modelo de arbitraje expedito y de baja cuantía del CAE; Centro de Arbitraje Empresarial.',
            footer_one_two:'Para mas información accede a,',

            footer_two:'Confirma con nuestro Prestador de servicios de certificación PSC ( Seguridata Privada S.A. de C.V. ) la validez de los documentos firmados por NOTARYNET en la siguiente liga',
            footer_three:'NOTARYNET es desarrollado y administrado por',
        },
        detail:{
            cost:'Costo',
            credits:'créditos',
            description:'Descripción',
            use_doc:'Utilizar este documento',
            display_format:'Vizualizar formato',
        },
        contact:{
            contact:'Contacto',
            qustions:'¿Tienes preguntas?',
            send_ms:'Envíanos un mensaje o comunicate con nosotros.',
            address:'Dirección',
            phone:'Teléfono',
            email:'Correo',
            follow:'Síguenos',
            name_input:'Nombre completo',
            email_input:'Correo electrónico',
            msg:'Mensaje',
            send:'ENVIAR',

        },
        requestinvoice:{
            request_invoice:'Request your invoice',
            date:'Fecha de compra',
            email:'Correo electrónico',
            business:'Razón Social',
            address:'Dirección',
            state:'Estado',
            select_option:'Selecciona una opción',
            town:'Ciudad',
            zipcode:'Código postal',
            send:'ENVIAR',
            accept:'Aceptar',
        },
        login:{
            login:'Iniciar Sesión',
            email:'Correo electrónico',
            password:'Contraseña',
            sign_up:'¿ No tienes una cuenta? Registrate.',
            forgot_pass:'¿Olvidó su contraseña?',
            access:'Acceder',
        },
        resetpassword:{
            recover:'Recuperar contraseña',
            write:'Escriba su correo electrónico. Le enviaremos un mensaje con los pasos para recuperar su contraseña.',
            email:'Correo electrónico',
            remember:'¿Recuerda su contraseña? ¡Acceder!',
            accept:'Aceptar',
        },
        register:{
            register:'Registrarse',
            basic_info:'INFORMACIÓN BASICA',
            fullname:'Nombre completo',
            phone:'Teléfono',
            write_phone:'Escribe tu Teléfono',
            email:'Correo electrónico',
            write_email:'Escribe tu Correo electrónico',
            to_whom:'¿ A NOMBRE DE QUIEN EMITES DOCUMENTOS?',
            to_whose:'¿ A NOMBRE DE QUIEN FIRMARAS ESTE DOCUMENTO?',
            physical_p:'Persona fisica',
            moral_p:'Persona moral',
            businessname:'Razon social',
            write_businessname:'Escribe tu Razon social',
            location_company:'UBICACIÓN DE LA EMPRESA',
            location:'UBICACIÓN',
            street:'Calle',
            write_street:'Escribe la calle',
            num_ext:'Número exterior ',
            write_num_ext:'Escribe el número exterior',
            num_int:'Número interior',
            write_num_int:'Escribe el número interior',
            neighborhood:'Colonia',
            write_neighborhood:'Escribe la colonia',
            zip_code:'Código postal',
            write_zip_code:'Escribe el código postal',
            state:'Estado',
            town:'Ciudad',
            select_option:'Selecciona una opción',

            access_sistem:'ACCESO A ESTE SISTEMA, CREA UNA CONTRASEÑA',
            pass:'Contraseña',
            write_pass:'Escribe tu Contraseña',
            confim_pass:'Confirmar tu contraseña',
            confirm_pass:'Confirma tu contraseña',
            the_sing:'A continuación firma dentro del recuadro lo mas parecido posible a la firma de tu documento de identificación oficial ( INE vigente o Pasaporte Vigente)',
            add_signature:'AGREGA UNA FIRMA',
            quit_signature:'Quitar firma',
            terms:'He leído y acepto los Términos y condiciones del',
            already_account:'¿Ya tiene una cuenta?',
            create_account_sing:'Crear cuenta y proceder a la firma',
            create_account:'Crear una cuenta',
        },
        account:{
            index:{
                documents:'Documentos',
                welcome:'Bienvenido',
                myinfo:'Mi Información básica',
                mydocs:'Mi Documentación',
                mylog:'Mi Logo',
                mysing:'Mi firma',
                mypass:'Mi contraseña',
                docs_sing:'Documentos a firmar',
                contacts:'Directorio de contactos',
                buy_credits:'Comprar créditos',
                history_pay:'Historico de pagos',
                logout:'Cerrar sesión',
            },
            basic_info:{
                my_basic_info:'My basic information',
                subtitle:'Toda la información es mandatoria y sera verificada, de lo contrario no se podrán emitir documentos.',
                email:'Correo electrónico',
                fullname:'Nombre completo',
                phone:'Teléfono',
                street:'Calle',
                num_ext:'Número exterior ',
                num_int:'Número interior',
                neighborhood:'Colonia',
                zip_code:'Código postal',
                state:'Estado',
                town:'Ciudad',
                select_option:'Selecciona una opción',
                save_changes:'Guardar cambios',
                foreing:'Mi dirección está fuera de México',
                country:'Pais',
            },
            mylogo:{
                mylogo:'Mi logo (Opcional)',
                subtitle:'Agrega el logo de tu marca comercial o empresa para que este aparezca en los documentos a certificar, este logo aparecera en la parte superior de los mismos.',
                extention:'Agrega una imagen JPG o PNG',
                quit:'Quitar',
                save_logo:'Guardar logo',

            },
            mysignature:{
                title:'Mi firma',
                subtitle:'Esta rubrica ser tomada para referencia para la firma de todos los próximos documentos que realices.',
                new_sing:'AGREGA NUEVA FIRMA',
                save_sing:'Guardar firma',
                sing_equal:'Firma igual que en tu INE',
                save:'Guardar',
                clean:'Limpiar'
            },
            password:{
                title:'Mi Contraseña',
                current_password:'Escriba su actual contraseña',
                new_password:'Escriba su nueva contraseña',
                new_password_confirm:'Vuelva a escribir su nueva contraseña',
                save_password:'Cambiar contraseña',
            },
            contacts:{
                title:'Contactos',
                add_contact:'Agregar contacto',
                subtitle:'Los contactos son quienes llenaran el documento contigo, ellos recibirán un correo para acceder al sistema de NOTARIONET y llenar sus datos para firmar digitalmente.',
                search:'Buscar contacto...',
                no_contacts:'No existen contactos en tu directorio',

                email:'Correo electronico',
                street:'Calle y número exterior',

                full_name:'Nombre completo',
                phone:'Teléfono',
                contact_exist:'Este contacto ya existe en nuestra base de datos, ya no es necesario que captures su información ',
                edit_contact:'Editar contacto',

                neighborhood:'Colonia',
                zip_code:'Código postal',
            },
            buycredits:{
                title:'Comprar créditos',
                select:'Seleccionar',
                selected:'Selecionado',
                select_option:'Seleccione una opción',
                info_pay:'Información de pago',
                deposit:'Deposito - Transferencia',
                card:'Tarjeta de crédito/débito',
                card_details:'Detalles de tarjeta',
                bank:'BANCO',
                headline:'TITULAR',
                send_proof:'Favor de enviarnos el comprobante de pago al siguiente correo',
                process_order:'Procesar pedido',
                done:'Entendido',
            },
            history_payment:{
                title:'Historico de pagos',
                id_compra:'ID de compra',
                package:'Paquete comprado',
                total_credits:'Total de créditos',
                date:'Fecha y hora de compra',
                validity:'Vigencia',
                status:'Estatus',
                payed:'Pagado',
                outstanding:'Pendiente de pago',
                accept:'Aceptar',
            },
            documents:{
                title:'Documentos',
                subtitle:'Gestiona y rastrea todos tus documentos digitales',
                search_placeholder:'Buscar documentos...',
                all_documents:'Todos',
                signed:'Firmados',
                pending:'Pendientes',
                cancelled:'Cancelados',
                total_documents:'Total de Documentos',
                no_documents:'No se encontraron documentos',
                no_documents_description:'Aún no has creado ningún documento. Comienza creando tu primer documento.',
                create_first_document:'Crear Primer Documento',
                view:'Ver',
                sign:'Firmar',
                download:'Descargar',
                cancel:'Cancelar',
                cancel_document:'Cancelar Documento',
                cancel_confirm:'¿Estás seguro de que quieres cancelar este documento? Esta acción no se puede deshacer.',
                cancelled_successfully:'Documento cancelado exitosamente',
                cancel_error:'Error al cancelar el documento',
                load_error:'Error al cargar los documentos',
                view_document:'Ver Documento',
                aviable_credits:'créditos disponibles',
                new_document:'Nuevo documento',
                buy_credits:'Comprar créditos',
                complete_info:'Debes de completar tu información',
                account_auth:'Tu cuenta cuenta debe estar autorizada antes de crear un documento',

                waiting_signature:'Esperando firma',
                pending_sign:'Pendientes por firmar',
                resend:'Reenviar',
                document_type:'Tipo de documento',
                date_realization:'Fecha de realización',
                contractor:'Contratante',
                counterpart:'Contraparte',
                signature_date:'Fecha de firma de',
                cancel:'Cancelar documento',
                sign:'Firmar',
                view_document:'Ver documento',
                cancellation_folio:'Folio de cancelación',
                date_cacelation:'Fecha de cancelación',

                modal_sing_title:'Da click para firmar de manera segura',
                modal_sing_subtitle:'Este documento no tiene validez hasta estar firmado completamente',
                accept:'Aceptar',

                folder_destination:'Carpeta de destino',
                select_option:'Seleccionar una opción',
                move:'Mover',
                newfolder:'Nueva carpeta',
                all:'Todos',
                move_to_folder:'Mover a carpeta',
                delete_folder:'Eliminar carpeta',
                folder:'Carpeta',
                folder_name:'Nombre de la carpeta',
                save:'Guardar',
                sign_less:'Debes registrar tu firma antes de firmar'
            },
        },
        credits:{
            title:'Selecciona un paquete de créditos',
            select:'Seleccionar',
            selected:'Selecionado',
            select_option:'Seleccione una opción',
            info_pay:'Información de pago',
            deposit:'Deposito - Transferencia',
            card:'Tarjeta de crédito/débito',
            card_details:'Detalles de tarjeta',
            bank:'BANCO',
            headline:'TITULAR',
            send_proof:'Favor de enviarnos el comprobante de pago al siguiente correo',
            process_order:'Procesar pedido',
            process_pay:'Procesar pago',
            done:'Entendido',
        },
        new_document:{
            title:'Nuevo documento',
            select_type:'Selecciona el tipo de documento',
            select_option:'Selecciona una opción',
            document_type:'Tipo de documento',
            description:'Descripción',
            description_con:'Puedes firmar capturas de pantalla de conversaciones, mensajes de texto, correos electrónicos y/o cualquier otro medio multimedia al que desees darle validez legal.',
            next:'Siguiente',
            previous:'Anterior',
            counterpart_data:'Datos de la contraparte',
            select_contacto:'Selecciona un contacto existente en tu directorio, o agrega uno nuevo. Los contactos son quienes firman el documento certificado:',
            search_contact:'Buscar contacto...',
            i_manager:'Soy el gestor de este documento, yo no realizo firmas.',
            phone:'Telefono',
            email:'Correo electronico',
            full_name:'Nombre completo',
            address:'Dirección',
            no_contacts:'No existen contactos en tu directorio',
            add_contact:'Agregar contacto',
            add_info_complete:'Agrega la información siguiente para completar tu documento',
            document_body:'Cuerpo del documento',
            select_element:'Selecciona el elemento a firmar',
            i_understand:'Comprendo que la imagen o documento a publicar se realiza de buena fe y que NOTARIONET no tiene ninguna responsabilidad sobre lo publicado.',
            reference_images:'Imagenes de referencia',
            add_image:'Agregar imagen',
            images_comments:'Comentarios',
            images_delete:'Eliminar',
            review:'Revisar',
            legal_support:'RESPALDO JURIDICO: La imagen mostrada a continuación es certificada por sello de tiempo y certificado digital de NOTARIONET y cumple con las normas NOM151 SCFI 2016 de la Secretaría de economía, el servicio de emisión de certificados digitales DOF 20/06/2011, el servicio de emisión de sellos digitales de tiempo de DOF 14/12/2011 y el servicio de digitalización de documentos en soporte físico como tercero legalmente autorizado TLA DOF 03/12/2019',
            finish:'Finalizar',
            sign:'Firmar',
            finished_document:'Documento terminado',
            completed_successfully:'Finalizado exitosamente',
            signed_document:'Documento firmado',
            signed_media:'Elemento multimedia firmado',
            go_to_documents:'Ve a la seccion " Documentos" de tu sesion para poder vizualizarlo.',
            signed_document_success:'Documento firmado exitosamente',
            will_send:'Sera enviado a tu contraparte para que sea firmado. Este documento puedes verlo en el apartado de " Documentos " de tu sesion',
            no_valid:'Este documento no tiene validez hasta estar firmado completamente',
            image:'Imagen',
            the_sign:'A continuación firma dentro del recuadro similar a la firma de referencia inicial que capturaste en el registro. Si la firma no es similar no podrás certificar documentos',

        }

    }

}
export default messages;
