<template lang="html">
  <div id="info-page-s1">
    <section class="placed-backg banner-section" v-bind:style="{ backgroundImage: 'url(https://notarionet.com/public/images/pages/documents/banner-1.jpg)' }"></section>

    <section class="container text-justify main-section" v-if="$i18n.locale == 'en'">
      <h1 class="title-s-1">Legal validity of electronic document</h1>

      <p>
        In Article 210 A (of the Federal Code of Civil Procedures) the information generated by communication that is recorded in electronic or optical media, or in any other technology, is recognized as evidence. In order to assess the probative part of the information referred to in the preceding paragraph, the reliability of the method in which it was generated, communicated, received or archived will be primarily estimated and, where appropriate, if it is possible to attribute the content to the obligated persons. of the relative information and be accessible for further consultation.
      </p>
      <p>
        When the law requires that a document be preserved and presented in its original form, this requirement will be satisfied if it is proven that the information generated, communicated, received or filed by optical electronic means or any other technology has remained intact and unaltered from the date of moment in which it was generated for the first time in its final form and this can be accessible for subsequent consultation.
      </p>
      <br />
      <p>
        An electronic document has the same value as a private document and, consequently, its probative value consists in the fact that it has a content that appears on a support or container, and that the requirements for notarization and signature concur, with certain particularities: the support it is computational, uses technological writing means or binary machine languages ​​and is attributable to whoever imitates it and types the keys, keys, or magnetic codes (which are more secure than handwritten signatures).
      </p>
      <p>
        Therefore, the electronic document is considered to be those data or information that have legal relevance, which are transmitted or recorded by electronic means, data or by means of simple sound supports, especially through digital processing.
      </p>
      <br />
      <p>
        On the other hand, the Federal Civil Code provides:<br />
        Article 1803. Consent can be express or implied, for this the following will apply:<br />
        <strong>I.</strong> It will be express when the will is expressed verbally, in writing, by electronic or optical means or by any other technology, or by unequivocal signs, and<br />
        <strong>II.</strong> The tacit will result from facts or acts that presuppose it or that authorize it to be presumed, except in cases in which by law or by agreement the will must be expressly stated.
      </p>
      <br />
      <p>
        On the other hand, the Federal Code of Civil Procedures establishes, among other things, within the means of evidence, the following:<br />
        The information generated or communicated that is recorded in electronic, optical or any other technology. In order to assess the probative force of the information referred to in this article, the reliability of the method in which it was generated, communicated, received or archived will be primarily estimated, or as the case may be, if it is possible to attribute the content to the obligated persons. of the relative information and be accessible for subsequent
      </p>
    </section>
    <section class="container text-justify main-section" v-else>
      <h1 class="title-s-1">Validez legal de documento electrónico</h1>

      <p>
        El artículo 210 A del CFPC y su correlativo 335 del CNPCF reconocen como medio de prueba la información generada o comunicada en medios electrónicos, ópticos o tecnológicos. Su valor probatorio depende de la fiabilidad del método empleado, la posibilidad de atribuir el contenido a las partes obligadas y de que la información se mantenga íntegra, inalterada y accesible.
      </p>
      <p hidden>
        Cuando la ley requiera que un documento sea conservado y presentado en su forma original ese requisito quedará satisfecho si se acredita que la información generada, comunicada, recibida o archivada por medios electrónicos ópticos o de cualquier otra tecnología se ha mantenido íntegra e inalterada a partir del momento en que se generó por primera vez en su forma definitiva y ésta pueda ser accesible para su ulterior consulta”.
      </p>
      <br />
      <p>
        Un documento electrónico tiene el mismo valor que un documento privado siempre que cumpla con los requisitos de escrituración y firma, utilizando soportes informáticos y claves electrónicas que ofrecen mayor seguridad que las firmas manuscritas.
      </p>
      <br />
      <p>
        Se entiende por documento electrónico cualquier dato o información con relevancia jurídica transmitido o registrado en medios digitales, incluidos archivos de audio u otros generados mediante procesamiento tecnológico.
      </p>
      <br />
      <p hidden>
        Por otra parte, el Código Civil Federal dispone:<br />
        Artículo 1803. El consentimiento puede ser expreso o tácito, para ello se estará a lo siguiente:<br />
        <strong>I.</strong> Será expreso cuando la voluntad se manifiesta verbalmente, por escrito, por medios electrónicos, ópticos o por cualquier otra tecnología, o por signos inequívocos, y<br />
        <strong>II.</strong> El tácito resultará de hechos o de actos que lo presupongan o que autoricen a presumirlo, excepto en los casos en que por ley o por convenio la voluntad deba manifestarse expresamente.
      </p>
      <p>
        Asimismo, el artículo 1803 del CCF establece que el consentimiento puede ser expreso, cuando se manifiesta verbalmente, por escrito o por medios electrónicos, ópticos o tecnológicos; o tácito, cuando deriva de hechos que lo presuponen, salvo en los casos en que la ley o el convenio exijan manifestación expresa.
      </p>
      <br />
      <p hidden>
        Por otra parte, el Código Federal de Procedimientos Civiles establece, entre otras cosas, dentro de los medios probatorios, lo siguiente:<br />
        La información generada o comunicada que consten en medios electrónicos, ópticos o en cualquier otra tecnología. Para valorar la fuerza probatoria de la información a que se refiere este artículo, se estimará primordialmente la fiabilidad del método en que haya sido generada, comunicada, recibida o archivada, o como en su caso, si es posible atribuir a las personas obligadas el contenido de la información relativa y ser accesible para su ulterior
      </p>
    </section>

  </div>
</template>

<script>
export default {
}
</script>
