<template lang="html">
  <div id="info-page-s2">

    <section class="container oversized-container text-justify main-section">
      <div class="row align-items-center">
        <div class="col-lg-6 order-2 order-lg-0 mt-2 mt-lg-0 col-image">
          <img src="https://notarionet.com/public/images/pages/about-us/image.jpg" class="slide-in-left">
        </div>

        <div class="col-lg-6 col-info" v-if="$i18n.locale == 'en'">
          <h1 class="title-s-1">OUR COMPANY</h1>

          <p>
            NOTARIONET is a company created by lawyers and businessmen with more than 30 years of experience and with the intention of simplifying the process of signing contracts and documents of all kinds.
          </p>
          <p class="mt-3">
            Our mission is to digitize official documents and streamline the signing, storage and consultation process.
          </p>
          <p class="mt-3">
            NOTARIONET has state-of-the-art technology that will change the legal industry by speeding up general processes and making documents more secure.
          </p>
        </div>

        <div class="col-lg-6 col-info" v-else>
          <h1 class="title-s-1" style="font-size: 40px;">NUESTRA EMPRESA</h1>

          <p>
            NOTARIONET es una empresa creada por abogados y empresarios con mas de 30 años de experiencia y con la intención de simplificar el proceso de la firma de contratos y documentos de todo tipo.
          </p>
          <p class="mt-3">
            Tenemos la misión de digitalizar los documentos oficiales y eficientar el proceso de firma, almacenado y consulta.
          </p>
          <p class="mt-3">
            NOTARIONET cuenta con tecnología de punta que cambiará la industria legal, acelerando los procesos y volviendo más seguros los documentos.
          </p>
        </div>
      </div>
    </section>

  </div>
</template>

<script>
export default {
}
</script>

<style>
    #info-page-s2 .main-section{
        padding-top: 100px;
        padding-bottom: 100px;
    }
    .slide-in-left {
        -webkit-animation: slide-in-left 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
                animation: slide-in-left 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
    }
    /* ----------------------------------------------
    * Generated by Animista on 2025-9-4 13:1:10
    * Licensed under FreeBSD License.
    * See http://animista.net/license for more info.
    * w: http://animista.net, t: @cssanimista
    * ---------------------------------------------- */

    /**
    * ----------------------------------------
    * animation slide-in-left
    * ----------------------------------------
    */
    @-webkit-keyframes slide-in-left {
    0% {
        -webkit-transform: translateX(-1000px);
                transform: translateX(-1000px);
        opacity: 0;
    }
    100% {
        -webkit-transform: translateX(0);
                transform: translateX(0);
        opacity: 1;
    }
    }
    @keyframes slide-in-left {
        0% {
            -webkit-transform: translateX(-1000px);
                    transform: translateX(-1000px);
            opacity: 0;
        }
        100% {
            -webkit-transform: translateX(0);
                    transform: translateX(0);
            opacity: 1;
        }
    }

</style>
