<template lang="html">
  <div id="info-page-s2">

    <section class="container oversized-container text-justify py-lg-3 main-section">
      <div class="row align-items-center">
        <div class="col-lg-7 col-info" v-if="$i18n.locale == 'en'">
          <h1 class="title-s-1">ELECTRONIC DOCUMENT DISPUTE RESOLUTION</h1>

          <p>
            The Business Arbitration Center is a private institution whose purpose is to provide arbitration administration services and other alternative dispute resolution mechanisms in accordance with the provisions of these Regulations.
          </p>
          <p class="mt-3">
            The CAE does not resolve by itself the controversies that are raised. Its mission is to enforce these Regulations and any other Regulations issued by the General Council.
          </p>
          <p class="mt-3">
            The CAE exercises its functions through one or more case managers, appointed by the General Council.
          </p>
          <p class="mt-3">
            When the parties have agreed that the disputes between them that derive from or are related to a certain legal, contractual or non-contractual relationship, be submitted to CAE arbitration in accordance with the Arbitration Regulations of the Business Arbitration Center, said disputes will be resolved. in accordance with the CAE Arbitration Rules in force on the date the proceeding begins, unless the parties agree to submit to the CAE Arbitration Rules in force on the date of the arbitration agreement.
          </p>
        </div>

        <div class="col-lg-7 col-info" v-else>
          <h1 class="title-s-1">SOLUCIÓN DE CONFLICTOS DE DOCUMENTOS ELECTRÓNICOS</h1>

          <p>
            El Centro de Arbitraje Empresarial S.C.P. (“CAE”) es una institución privada cuyo objeto es prestar el servicio de administración de arbitrajes y otros mecanismos alternativos de solución de controversias de conformidad con lo dispuesto por este Reglamento.
          </p>
          <p class="mt-3">
            El CAE no resuelve por sí mismo las controversias que le son planteadas. Su misión es hacer cumplir el presente Reglamento y cualquier otro Reglamento que emita el Consejo General.
          </p>
          <p class="mt-3">
            El CAE ejerce sus funciones a través de uno o más administradores del caso, nombrados por el Consejo General.
          </p>
          <p class="mt-3">
            Cuando las partes hayan acordado que las controversias entre ellas que deriven de o guarden relación con una determinada relación jurídica, contractual o no contractual, se sometan al arbitraje del CAE de conformidad con el Reglamento de Arbitraje del Centro de Arbitraje Empresarial S.C.P. (“CAE”)”, dichas controversias se resolverán de conformidad con el Reglamento de Arbitraje del CAE vigente en la fecha de inicio del procedimiento, a menos que las partes acuerden someterse al Reglamento de Arbitraje del CAE vigente a la fecha del acuerdo de arbitraje.
          </p>
        </div>


        <div class="col-lg-5 mt-2 mt-lg-0 col-image">
          <img class="max-75 slide-in-right" src="https://notarionet.com/public/images/pages/cae/image.jpg">
        </div>
      </div>
    </section>

  </div>
</template>

<script>
export default {
}
</script>

<style>
    .slide-in-right {
        -webkit-animation: slide-in-right 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
                animation: slide-in-right 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
    }
    /* ----------------------------------------------
    * Generated by Animista on 2025-9-4 12:39:54
    * Licensed under FreeBSD License.
    * See http://animista.net/license for more info.
    * w: http://animista.net, t: @cssanimista
    * ---------------------------------------------- */

    /**
    * ----------------------------------------
    * animation slide-in-right
    * ----------------------------------------
    */
    @-webkit-keyframes slide-in-right {
        0% {
            -webkit-transform: translateX(1000px);
                    transform: translateX(1000px);
            opacity: 0;
        }
        100% {
            -webkit-transform: translateX(0);
                    transform: translateX(0);
            opacity: 1;
        }
    }
    @keyframes slide-in-right {
        0% {
            -webkit-transform: translateX(1000px);
                    transform: translateX(1000px);
            opacity: 0;
        }
        100% {
            -webkit-transform: translateX(0);
                    transform: translateX(0);
            opacity: 1;
        }
    }
</style>
